### ISSUE TITLE
Historical data is not working as documented

### ISSUE THREAD

**Issue by href** [interactivethings/swiss-maps#20]
I tried all of the following commands with varying years and the result is always the same (the hash of all resulting files matches):

* `make topo/ch-municipalities.json YEAR=2014`
* `make topo/ch-municipalities.json YEAR=2014 PROPERTIES=id,name`
* `make all YEAR=2014 PROPERTIES=id,name`

When generating the files with the name of the municipality I can also verify that the result is not correct with historical data like this one:

The municipality "Calanca" in Graubünden only exists since 2015, when it formed out of a number of other municipalities: https://en.wikipedia.org/wiki/Calanca

In all datasets however, "Calanca" is present. Not say "Arvigo".

I tried to find the cause of the problem but I'm afraid due to my limited understanding of the matter (and make) I didn't get anywhere :)

**Comment by herrstucki** [comment]
Running `make clean-generated` before switching the year should help.

**Comment by href** [comment]
Thanks, that's it! I was removing the topo folder each time, but it didn't occur to me to check the other files :sweat:

**Comment by herrstucki** [comment]
Thanks for verifying! I guess it wasn't obvious and I've added a note to the README.

Also it got me thinking about #10 again …
