### ISSUE TITLE
Add Year 2016

### ISSUE THREAD

**Issue by href** [interactivethings/swiss-maps#22]
The new swissBOUNDARIES3D files are out: http://www.swisstopo.admin.ch/internet/swisstopo/de/home/products/landscape/swissBOUNDARIES3D.html

However, the VECTOR200 doesn't seem to be up to date. Do they need to be of the same year?

**Comment by herrstucki** [comment]
Yay :tada:

The VEC200 boundaries are usually included in the swissBOUNDARIES3D download.

**Comment by href** [comment]
There are some files in a V200 folder, but they are not named the way yours are. I got `VECTOR200_BEZIRKSGEBIET.*` and you got `VEC200_Commune.*` for example. The sizes of the files indicate that those are not the same files with different names.

I found your `VEC200_*` files on the following site, this is why I'm assuming it's two different downloads:
http://www.swisstopo.admin.ch/internet/swisstopo/de/home/products/landscape/vector200.html

So I'm a bit confused :sweat:

**Comment by herrstucki** [comment]
I quickly had a look: they are the right files, but just named differently. Commune = Hoheitsgebiet.

**Comment by herrstucki** [comment]
I'll add them when I have a free minute (probably over the weekend). Or if you want, go ahead and create a PR :smile:

**Comment by href** [comment]
I wanted to send a PR your way anyway, I just wasn't sure I had the right data :)
So I'll have a stab at it today.

**Comment by href** [comment]
Nope I give up. I think you better have a look at it. The files seem to differ from last year:

* The commune file now contains a lot more detail about towns outside Switzerland. Not sure if there's some manual processing required to get rid of these details.
* There's no equivalent for the protected area file from what I can tell. I know it's just lakes but in previous years, this data seems to have been available?
* The VEC200_ADMLVL* files also have no equivalent. There are dbf files but for some reason QGIS doesn't recognize them (it works with last year's data).

I'm afraid I'm lost. Probably doesn't help that I have not one clue about GIS ;)

**Comment by markdrayton** [comment]
Has anyone had any luck in tracking down the VEC200 files? I downloaded the 2019 data but the VEC200 files don't seem to be in the boundaries data. I also noticed in the notes for the [2017 release](https://www.swisstopo.admin.ch/content/swisstopo-internet/de/home/products/landscape/boundaries3d/_jcr_content/contentPar/tabs/items/dokumente/tabPar/downloadlist_1294035/downloadItems/21_1487685933217.download/swissBOUNDARIES3D_release2017_de_barrierefrei.pdf) (and subsequent releases) there is a paragraph saying:

> Since the 2016 issue, the swissBOUNDARIES3D product has also been pushing the limits
of the data set VECTOR200. These limits are generalized and suitable for
small-scale representations. The attributes of swissBOUNDARIES3D and
VECTOR200 Boundaries are coordinated.

This is translated via Google as I don't speak German. But I wonder if it's some statement on the VEC200 stuff being subsumed into the rest of the data somehow? Unfortunately I know close to nothing about how his data is structured or where to start digging things out.

**Comment by href** [comment]
I can't help you much with tracking down these files, but do let me provide you with a non-butchered translation of the paragraph you're referencing:

> Since the 2016 issue, the product swissBOUNDARIES3D also includes the borders of the VECTOR200 dataset. These boundaries are generalised and suitable for small-scale display. The attributes of swissBOUNDARIES3D and VECTOR200 have been made to align with each other.

**Comment by markdrayton** [comment]
Thanks for the translation! It makes more sense now.

**Comment by herrstucki** [comment]
Nowadays, I'd probably recommend the boundaries from the Federal Office of Statistics: https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/geostat/geodaten-bundesstatistik/administrative-grenzen/generalisierte-gemeindegrenzen.html

They have different licensing but should be fine for non-commercial use (i.e. where you don't re-sell the geodata itself).

**Comment by markdrayton** [comment]
Ah, thanks. I'll take a look there.

**Comment by Martouf** [comment]
I adapted the script for 2020.
The data are here: https://shop.swisstopo.admin.ch/fr/products/landscape/boundaries3D

Swisstopo has changed the name of the files:
2019: VECTOR200_HOHEITSGEBIET.shp → 25.7Mo
2020: swissTLMRegio_HOHEITSGEBIET_LV03.shp → 25.7 Mo.

I put the files in the old "V200" folder.

I update the makefile (the 2016 version): 
build/ch/municipalities.shp: src/V200/$(YEAR)/swissTLMRegio_HOHEITSGEBIET_LV03.shp

it works to export all municipalites in topojson.  (make all)
Be careful to use the old "topojson" script. Since 2019, topojson is deprecated and replaced by topojson-client, topojson-server or topojson-simplify...

(npm WARN deprecated topojson@1.6.27: Use topojson-client, topojson-server or topojson-simplify directly. )

Thanks for the scripts.
