### ISSUE TITLE
Pull data from Swiss open data portal

### ISSUE THREAD

**Issue by herrstucki** [interactivethings/swiss-maps#6]
I'd love to use the data from http://opendata.admin.ch/de/dataset?tags=verwaltungseinheiten instead of bundling the source files in this repository.

But:
- Although they list different datasets for the boundaries, they all contain the same data. This is not really a problem here but it may change in the future.
- The data is in one monolithic zip file which contains data in both coordinate systems and all formats they provide. There's no way to only request one format at a time.

Until that changes I'll probably keep bundling the necessary shapefiles.

**Comment by dbruehlmeier** [comment]
That would be great! 👍

**Comment by loleg** [comment]
Yep. It's been 5 years, but this repo is still relevant, useful, and used. But a fresh checkout shouldn't weigh 600 MB.

```
oleg@localhost ~/L/g/swiss-maps> du -sh
599M	.
```
